### ISSUE TITLE
Issue with simple examples and event store 5

### ISSUE THREAD

**Issue by Nek-** [prooph/event-store-client#129]
Hello I tried to follow the documentation of [eventstore](https://eventstore.com/docs/getting-started/index.html?tabs=tabid-3%2Ctabid-dotnet-client%2Ctabid-dotnet-client-connect%2Ctabid-5). With the idea in mind of adding PHP aside of .net & jvm examples :muscle: .

But event-store-client simple usage seems to have issues:

```bash
docker run --name eventstore-node -it -p 2113:2113 -p 1113:1113 eventstore/eventstore
```

```php
\Amp\Loop::run(function () {
    $connection = EventStoreConnectionFactory::createFromUri(Uri::fromString('tcp://admin:changeit@localhost:1113'));

    // issue 1: onConnected is never fired in this case
    // Same for only connection and closing...
    $connection->onConnected(function (): void {
        echo 'connected' . PHP_EOL;
    });

    $connection->onClosed(function (): void {
        echo 'connection closed' . PHP_EOL;
    });

    yield $connection->connectAsync();

    // Example from official doc, translated to PHP, does not work here.
    $streamName = 'newstream';
    $eventType = 'event-type';
    $data = '{ "a": "1" }';
    $metadata = '{}';
    $eventPayload = new EventData(EventId::generate(), $eventType, true, $data, $metadata);
    yield $connection->appendToStreamAsync($streamName, ExpectedVersion::ANY, [$eventPayload]);

    $connection->close();
});
```

And the only thing I get is an exeception/failure:
```
connection closed
PHP Fatal error:  Uncaught Prooph\EventStoreClient\Exception\ConnectionClosedException: Connection 'faadad837aaac842830b6957702454ba' was closed in eventstore/vendor/prooph/event-store-client/src/Exception/ConnectionClosedException.php:20
Stack trace:
#0 eventstore/vendor/prooph/event-store-client/src/Internal/OperationsManager.php(72): Prooph\EventStoreClient\Exception\ConnectionClosedException::withName()
#1 eventstore/vendor/prooph/event-store-client/src/Internal/EventStoreConnectionLogicHandler.php(280): Prooph\EventStoreClient\Internal\OperationsManager->cleanUp()
#2 eventstore/vendor/prooph/event-store-client/src/Internal/EventStoreConnectionLogicHandler.php(357): Prooph\EventStoreClient\Internal\EventStoreConnectionLogicHandler->closeConnection()
#3 eventstore/vendor/prooph/event-store-client/src/Internal/EventStoreConnectionLogicHan in eventstore/vendor/prooph/event-store-client/src/Exception/ConnectionClosedException.php on line 20
```

I sorry if I made something wrong. I tried to go on gitter but it seems there's nobody there.

[edit]
After turning on the debug, it seems that I'm missing the `\ProtobufMessage` class.

```
[2020-05-01T17:18:47.859751+02:00] event-store-client.debug: TcpPackageConnection: [localhost:1113, 119b2ddd3191394eb010def00cb68ab3]: Error when processing TcpPackage Authenticated: Class 'ProtobufMessage' not found. Connection will be closed
```

How? Why? o.o I can't understand what should provide this class..

**Comment by Nek-** [comment]
I was trying to use the last version. I tagged `@dev` in composer. But it loaded the beta T_T. That's why.
