### ISSUE TITLE
Trying the example with server version 20.10.0.0, but can't connect

### ISSUE THREAD

**Issue by sleenen** [prooph/event-store-client#155]
Trying the example to subscribe to stream and enabled logging. It's trying to reconnect all the time and then fails. 
Any clue as to what is going on? Trying to get simple test/example setup to run.

This is the code:
```
<?php

/**
 * This file is part of `prooph/event-store-client`.
 * (c) 2018-2020 Alexander Miertsch <kontakt@codeliner.ws>
 * (c) 2018-2020 Sascha-Oliver Prolic <saschaprolic@googlemail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Prooph\EventStoreClient;

use Amp\Loop;
use Amp\Promise;
use Amp\Success;
use Prooph\EventStore\Async\EventStoreCatchUpSubscription;
use Prooph\EventStore\CatchUpSubscriptionSettings;
use Prooph\EventStore\EndPoint;
use Prooph\EventStore\ResolvedEvent;
use Prooph\EventStore\SubscriptionDropReason;
use Throwable;

require __DIR__ . '/vendor/autoload.php';

Loop::run(function () {
    $builder = new ConnectionSettingsBuilder();
    $builder->enableVerboseLogging();
    $builder->useConsoleLogger();

    $connection = EventStoreConnectionFactory::createFromEndPoint(
        new EndPoint('127.0.0.1', 1113),
        $builder->build()
    );

    $connection->onConnected(function (): void {
        echo 'connected' . PHP_EOL;
    });

    $connection->onClosed(function (): void {
        echo 'connection closed' . PHP_EOL;
    });

    yield $connection->connectAsync();

    yield $connection->subscribeToStreamFromAsync(
        'test',
        null,
        CatchUpSubscriptionSettings::default(),
        function (EventStoreCatchUpSubscription $subscription, ResolvedEvent $resolvedEvent): Promise {
            echo 'incoming event: ' . $resolvedEvent->originalEventNumber() . '@' . $resolvedEvent->originalStreamName() . PHP_EOL;
            echo 'data: ' . $resolvedEvent->originalEvent()->data() . PHP_EOL;

            return new Success();
        },
        function (EventStoreCatchUpSubscription $subscription): void {
            echo 'liveProcessingStarted on ' . $subscription->streamId() . PHP_EOL;
        },
        function (
            EventStoreCatchUpSubscription $subscription,
            SubscriptionDropReason $reason,
            ?Throwable $exception = null
        ): void {
            echo 'dropped with reason: ' . $reason->name() . PHP_EOL;

            if ($exception) {
                echo 'ex: ' . $exception->getMessage() . PHP_EOL;
            }
        }
    );
});
```

And the resulting output:
```
[2021-04-20T14:49:01.006211+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': enqueuing message StartConnectionMessage
[2021-04-20T14:49:01.006324+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': startConnection
[2021-04-20T14:49:01.006376+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': discoverEndPoint
[2021-04-20T14:49:01.006509+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': enqueuing message EstablishTcpConnectionMessage
[2021-04-20T14:49:01.006557+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': EstablishTcpConnection to [127.0.0.1:1113]
[2021-04-20T14:49:01.009582+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': enqueuing message StartOperationMessage
[2021-04-20T14:49:01.009671+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': StartOperation enqueue ReadStreamEventsForward, Stream: test, FromEventNumber: 0, MaxCount: 500, ResolveLinkTos: yes, RequireMaster: yes, 10, 7000
[2021-04-20T14:49:01.010000+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': EnqueueOperation WAITING for Operation ReadStreamEventsForward (092cde521c31284f965a39420246d96e): Stream: test, FromEventNumber: 0, MaxCount: 500, ResolveLinkTos: yes, RequireMaster: yes, retry count: 0, created: 2021-04-20T14:49:01.009887+00:00, last updated: 2021-04-20T14:49:01.009887+00:00
[2021-04-20T14:49:01.014990+00:00] event-store-client.debug: TcpPackageConnection: connected to [127.0.0.1:1113, 8f3b8ef2d987fe43b6f6b62944ba6f0c]
[2021-04-20T14:49:01.015188+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': enqueuing message TcpConnectionEstablishedMessage
[2021-04-20T14:49:01.015239+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': TCP connection to [127.0.0.1:1113, 8f3b8ef2d987fe43b6f6b62944ba6f0c] established
[2021-04-20T14:49:01.822399+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': enqueuing message TcpConnectionClosedMessage
[2021-04-20T14:49:01.822494+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': TCP connection to [127.0.0.1:1113, 8f3b8ef2d987fe43b6f6b62944ba6f0c] closed
[2021-04-20T14:49:02.023089+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': TimerTick checking reconnection...
[2021-04-20T14:49:02.023535+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': discoverEndPoint
[2021-04-20T14:49:02.023586+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': enqueuing message EstablishTcpConnectionMessage
[2021-04-20T14:49:02.023619+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': EstablishTcpConnection to [127.0.0.1:1113]
[2021-04-20T14:49:02.024085+00:00] event-store-client.debug: TcpPackageConnection: connected to [127.0.0.1:1113, d021a0ce71227246866f4f3f8c6d28f7]
[2021-04-20T14:49:02.024141+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': enqueuing message TcpConnectionEstablishedMessage
[2021-04-20T14:49:02.024179+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': TCP connection to [127.0.0.1:1113, d021a0ce71227246866f4f3f8c6d28f7] established
[2021-04-20T14:49:02.836745+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': enqueuing message TcpConnectionClosedMessage
[2021-04-20T14:49:02.836873+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': TCP connection to [127.0.0.1:1113, d021a0ce71227246866f4f3f8c6d28f7] closed
[2021-04-20T14:49:03.040266+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': TimerTick checking reconnection...
[2021-04-20T14:49:03.040417+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': discoverEndPoint
[2021-04-20T14:49:03.040493+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': enqueuing message EstablishTcpConnectionMessage
[2021-04-20T14:49:03.040551+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': EstablishTcpConnection to [127.0.0.1:1113]
[2021-04-20T14:49:03.041474+00:00] event-store-client.debug: TcpPackageConnection: connected to [127.0.0.1:1113, 6f5dcfe7e4502148aaefe548ebb46936]
[2021-04-20T14:49:03.041547+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': enqueuing message TcpConnectionEstablishedMessage
[2021-04-20T14:49:03.041593+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': TCP connection to [127.0.0.1:1113, 6f5dcfe7e4502148aaefe548ebb46936] established
[2021-04-20T14:49:03.855911+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': enqueuing message TcpConnectionClosedMessage
[2021-04-20T14:49:03.855995+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': TCP connection to [127.0.0.1:1113, 6f5dcfe7e4502148aaefe548ebb46936] closed
[2021-04-20T14:49:04.060799+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': TimerTick checking reconnection...
[2021-04-20T14:49:04.060893+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': discoverEndPoint
[2021-04-20T14:49:04.060942+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': enqueuing message EstablishTcpConnectionMessage
[2021-04-20T14:49:04.060979+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': EstablishTcpConnection to [127.0.0.1:1113]
[2021-04-20T14:49:04.061550+00:00] event-store-client.debug: TcpPackageConnection: connected to [127.0.0.1:1113, c03e2962f8daed48b226f5f12501d7c1]
[2021-04-20T14:49:04.061618+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': enqueuing message TcpConnectionEstablishedMessage
[2021-04-20T14:49:04.061664+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': TCP connection to [127.0.0.1:1113, c03e2962f8daed48b226f5f12501d7c1] established
[2021-04-20T14:49:04.870074+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': enqueuing message TcpConnectionClosedMessage
[2021-04-20T14:49:04.870145+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': TCP connection to [127.0.0.1:1113, c03e2962f8daed48b226f5f12501d7c1] closed
[2021-04-20T14:49:05.074602+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': TimerTick checking reconnection...
[2021-04-20T14:49:05.074686+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': discoverEndPoint
[2021-04-20T14:49:05.074726+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': enqueuing message EstablishTcpConnectionMessage
[2021-04-20T14:49:05.074759+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': EstablishTcpConnection to [127.0.0.1:1113]
[2021-04-20T14:49:05.075225+00:00] event-store-client.debug: TcpPackageConnection: connected to [127.0.0.1:1113, c332aab3cea1734fa3d5092b65ec075d]
[2021-04-20T14:49:05.075278+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': enqueuing message TcpConnectionEstablishedMessage
[2021-04-20T14:49:05.075318+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': TCP connection to [127.0.0.1:1113, c332aab3cea1734fa3d5092b65ec075d] established
[2021-04-20T14:49:05.885017+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': enqueuing message TcpConnectionClosedMessage
[2021-04-20T14:49:05.885083+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': TCP connection to [127.0.0.1:1113, c332aab3cea1734fa3d5092b65ec075d] closed
[2021-04-20T14:49:06.090194+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': TimerTick checking reconnection...
[2021-04-20T14:49:06.090263+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': discoverEndPoint
[2021-04-20T14:49:06.090297+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': enqueuing message EstablishTcpConnectionMessage
[2021-04-20T14:49:06.090322+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': EstablishTcpConnection to [127.0.0.1:1113]
[2021-04-20T14:49:06.090710+00:00] event-store-client.debug: TcpPackageConnection: connected to [127.0.0.1:1113, 279613ff56c3c944963bc204aaf01e72]
[2021-04-20T14:49:06.090742+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': enqueuing message TcpConnectionEstablishedMessage
[2021-04-20T14:49:06.090767+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': TCP connection to [127.0.0.1:1113, 279613ff56c3c944963bc204aaf01e72] established
[2021-04-20T14:49:06.901379+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': enqueuing message TcpConnectionClosedMessage
[2021-04-20T14:49:06.901444+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': TCP connection to [127.0.0.1:1113, 279613ff56c3c944963bc204aaf01e72] closed
[2021-04-20T14:49:07.103948+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': TimerTick checking reconnection...
[2021-04-20T14:49:07.104021+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': discoverEndPoint
[2021-04-20T14:49:07.104056+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': enqueuing message EstablishTcpConnectionMessage
[2021-04-20T14:49:07.104082+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': EstablishTcpConnection to [127.0.0.1:1113]
[2021-04-20T14:49:07.104565+00:00] event-store-client.debug: TcpPackageConnection: connected to [127.0.0.1:1113, dc4008333520134a88dd7b7f21c5bb05]
[2021-04-20T14:49:07.104617+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': enqueuing message TcpConnectionEstablishedMessage
[2021-04-20T14:49:07.104656+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': TCP connection to [127.0.0.1:1113, dc4008333520134a88dd7b7f21c5bb05] established
[2021-04-20T14:49:07.912353+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': enqueuing message TcpConnectionClosedMessage
[2021-04-20T14:49:07.912428+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': TCP connection to [127.0.0.1:1113, dc4008333520134a88dd7b7f21c5bb05] closed
[2021-04-20T14:49:08.111865+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': TimerTick checking reconnection...
[2021-04-20T14:49:08.111947+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': discoverEndPoint
[2021-04-20T14:49:08.111993+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': enqueuing message EstablishTcpConnectionMessage
[2021-04-20T14:49:08.112031+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': EstablishTcpConnection to [127.0.0.1:1113]
[2021-04-20T14:49:08.112736+00:00] event-store-client.debug: TcpPackageConnection: connected to [127.0.0.1:1113, 28a2b57cfe8d2e4a87ea8709366f297d]
[2021-04-20T14:49:08.112856+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': enqueuing message TcpConnectionEstablishedMessage
[2021-04-20T14:49:08.112925+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': TCP connection to [127.0.0.1:1113, 28a2b57cfe8d2e4a87ea8709366f297d] established
[2021-04-20T14:49:08.925015+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': enqueuing message TcpConnectionClosedMessage
[2021-04-20T14:49:08.925074+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': TCP connection to [127.0.0.1:1113, 28a2b57cfe8d2e4a87ea8709366f297d] closed
[2021-04-20T14:49:09.128915+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': TimerTick checking reconnection...
[2021-04-20T14:49:09.128977+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': discoverEndPoint
[2021-04-20T14:49:09.129006+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': enqueuing message EstablishTcpConnectionMessage
[2021-04-20T14:49:09.129028+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': EstablishTcpConnection to [127.0.0.1:1113]
[2021-04-20T14:49:09.129417+00:00] event-store-client.debug: TcpPackageConnection: connected to [127.0.0.1:1113, 12de41613b32994c9cdcb08df39a3a19]
[2021-04-20T14:49:09.129453+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': enqueuing message TcpConnectionEstablishedMessage
[2021-04-20T14:49:09.129479+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': TCP connection to [127.0.0.1:1113, 12de41613b32994c9cdcb08df39a3a19] established
[2021-04-20T14:49:09.945226+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': enqueuing message TcpConnectionClosedMessage
[2021-04-20T14:49:09.945310+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': TCP connection to [127.0.0.1:1113, 12de41613b32994c9cdcb08df39a3a19] closed
[2021-04-20T14:49:10.148913+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': TimerTick checking reconnection...
[2021-04-20T14:49:10.149007+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': discoverEndPoint
[2021-04-20T14:49:10.149055+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': enqueuing message EstablishTcpConnectionMessage
[2021-04-20T14:49:10.149086+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': EstablishTcpConnection to [127.0.0.1:1113]
[2021-04-20T14:49:10.149616+00:00] event-store-client.debug: TcpPackageConnection: connected to [127.0.0.1:1113, f988512aeb68ae438955a1306f7fd4d5]
[2021-04-20T14:49:10.149670+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': enqueuing message TcpConnectionEstablishedMessage
[2021-04-20T14:49:10.149701+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': TCP connection to [127.0.0.1:1113, f988512aeb68ae438955a1306f7fd4d5] established
[2021-04-20T14:49:10.959360+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': enqueuing message TcpConnectionClosedMessage
[2021-04-20T14:49:10.959485+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': TCP connection to [127.0.0.1:1113, f988512aeb68ae438955a1306f7fd4d5] closed
[2021-04-20T14:49:11.158685+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': TimerTick checking reconnection...
[2021-04-20T14:49:11.158768+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': discoverEndPoint
[2021-04-20T14:49:11.158802+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': enqueuing message EstablishTcpConnectionMessage
[2021-04-20T14:49:11.158828+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': EstablishTcpConnection to [127.0.0.1:1113]
[2021-04-20T14:49:11.159291+00:00] event-store-client.debug: TcpPackageConnection: connected to [127.0.0.1:1113, 30fce9b9a0f385498c78eccf8c8e5ca7]
[2021-04-20T14:49:11.159339+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': enqueuing message TcpConnectionEstablishedMessage
[2021-04-20T14:49:11.159371+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': TCP connection to [127.0.0.1:1113, 30fce9b9a0f385498c78eccf8c8e5ca7] established
[2021-04-20T14:49:11.970397+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': enqueuing message TcpConnectionClosedMessage
[2021-04-20T14:49:11.970516+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': TCP connection to [127.0.0.1:1113, 30fce9b9a0f385498c78eccf8c8e5ca7] closed
[2021-04-20T14:49:12.173376+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': TimerTick checking reconnection...
[2021-04-20T14:49:12.173442+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': CloseConnection, reason Reconnection limit reached, exception <none>
dropped with reason: CatchUpError
ex: Connection 'c413ffa18a34a0429d9c8713f05e1bce' was closed
[2021-04-20T14:49:12.174053+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': CloseTcpConnection
[2021-04-20T14:49:12.174160+00:00] event-store-client.debug: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': IGNORED (state: Closed, internal conn.ID: {1:B}, conn.ID: 30fce9b9a0f385498c78eccf8c8e5ca7): TCP connection to [30fce9b9a0f385498c78eccf8c8e5ca7] closed
[2021-04-20T14:49:12.174192+00:00] event-store-client.info: EventStoreNodeConnection 'c413ffa18a34a0429d9c8713f05e1bce': Closed. Reason: Reconnection limit reached
connection closed
PHP Fatal error:  Uncaught Prooph\EventStore\Exception\ConnectionClosed: Connection 'c413ffa18a34a0429d9c8713f05e1bce' was closed in eventstore-client/vendor/prooph/event-store/src/Exception/ConnectionClosed.php:20
Stack trace:
#0 eventstore-client/vendor/prooph/event-store-client/src/Internal/OperationsManager.php(68): Prooph\EventStore\Exception\ConnectionClosed::withName('c413ffa18a34a04...')
#1 eventstore-client/vendor/prooph/event-store-client/src/Internal/EventStoreConnectionLogicHandler.php(276): Prooph\EventStoreClient\Internal\OperationsManager->cleanUp()
#2 eventstore-client/vendor/prooph/event-store-client/src/Internal/EventStoreConnectionLogicHandler.php(526): Prooph\EventStoreClient\Internal\EventStoreConnectionLogicHandler->closeConnection('Reconnection li...')
#3 eventstore-cl in eventstore-client/vendor/prooph/event-store/src/Exception/ConnectionClosed.php on line 20

Fatal error: Uncaught Prooph\EventStore\Exception\ConnectionClosed: Connection 'c413ffa18a34a0429d9c8713f05e1bce' was closed in eventstore-client/vendor/prooph/event-store/src/Exception/ConnectionClosed.php:20
Stack trace:
#0 eventstore-client/vendor/prooph/event-store-client/src/Internal/OperationsManager.php(68): Prooph\EventStore\Exception\ConnectionClosed::withName('c413ffa18a34a04...')
#1 eventstore-client/vendor/prooph/event-store-client/src/Internal/EventStoreConnectionLogicHandler.php(276): Prooph\EventStoreClient\Internal\OperationsManager->cleanUp()
#2 eventstore-client/vendor/prooph/event-store-client/src/Internal/EventStoreConnectionLogicHandler.php(526): Prooph\EventStoreClient\Internal\EventStoreConnectionLogicHandler->closeConnection('Reconnection li...')
#3 eventstore-cl in eventstore-client/vendor/prooph/event-store/src/Exception/ConnectionClosed.php on line 20
```

**Comment by prolic** [comment]
Please post the server logs, maybe this will give more details

**Comment by prolic** [comment]
close due to inactivity
